<div style="width:100%;float:left;font-size:10px;background-color:#fff;padding:10px;height:450px;">
Scarto.pl to nowy serwis na rynku ogłoszeń motoryzacyjnych. Został założony w 2013 roku. Naszym celem jest:

<ul>
<li> umożliwienie zamieszczania darmowych ogłoszeń</li>
<li> lepsza promocja ofert sprzedaży</li>
<li> możliwość zamieszczania dodatkowych mediów jak nakręcone przez właścicieli filmy samochodu</li>
</ul>
Pomimo że serwis pozostaje bezpłatny dokładamy starań, by zachował nowoczesną formę i był prosty w obsłudze. W razie pytań czy sugestii zapraszamy do kontaktu (kontakt@scarto.pl). 
</div>