<div style="width:100%;float:left;font-size:10px;background-color:#fff;padding:10px;">
<h1 style="font-size:14px;">REGULAMIN scarto.pl</h1>


<h2 style="font-size:12px;">I. O scarto.pl</h2>

<p>1. Niniejszy regulamin („Regulamin”) określa zasady korzystania przez użytkowników sieci Internet („Użytkownicy”) z serwisu internetowego scarto.pl, będącego ogólnopolską platformą handlową dla sprzedających i kupujących („Platforma”).</p>

<p>2. Celem Platformy jest ułatwienie Użytkownikom dokonywania transakcji sprzedaży, poprzez umożliwienie im zamieszczania ofert sprzedaży na Platformie („Oferty”), komunikowania się między sobą oraz dotarcia do szerokiego kręgu odbiorców. </p>
        
<h2 style="font-size:12px;">II. BRAK OPŁAT I PROWIZJI</h2>
        
<p>1. Korzystanie z Platformy jest bezpłatne.  </p>

<p>2. Platforma nie pobiera opłat za zamieszczanie Ofert. </p>

<p>3. Platforma nie pobiera prowizji od transakcji przeprowadzanych między Użytkownikami.</p>
    
<h2 style="font-size:12px;">III. KORZYSTANIE Z PLATFORMY</h2>

<p>1. Użytkownikiem Platformy może być osoba fizyczna, która ukończyła 18 rok życia, posiadająca pełną zdolność do czynności prawnych, osoba prawna lub jednostka organizacyjna nieposiadająca osobowości prawnej, ale mogąca we własnym imieniu nabywać prawa oraz zaciągać zobowiązania. </p>

<p>2. żytkownikami Platformy mogą być również osoby niepełnoletnie, które ukończyły 13 rok życia, ale nie ukończyły 18 lat, w zakresie, w jakim mogą nabywać prawa i zaciągać zobowiązania zgodnie z przepisami powszechnie obowiązującego prawa i z zastrzeżeniem, że wszelkie działania muszą odbywać się za zgodą ich opiekuna prawnego.  </p>

<p>3. Użytkownik jest zobowiązany do przestrzegania niniejszego Regulaminu. Skorzystanie przez Użytkownika z Platformy oznacza wyrażenie przez Użytkownika zgody na warunki określone w niniejszym Regulaminie.</p>

<p>4. Scarto.pl nie weryfikuje tożsamości Użytkowników i nie odpowiada za wiarygodność danych podawanych przez Użytkowników.</p>

<p>5. Użytkownicy, którzy zamieszczają Oferty lub są zainteresowani zakupem rzeczy będących przedmiotem Ofert, mają obowiązek podawania swoich prawdziwych danych osobowych.</p>

<p>6. Ponadto Użytkownik zobowiązany jest do:
            
            <ul>
            <li>Korzystania z Platformy w sposób niezakłócający jej funkcjonowania, w szczególności poprzez użycie określonego oprogramowania lub urządzeń;</li>
            <li>Niepodejmowania działań takich jak: rozsyłanie lub umieszczanie na Platformie niezamówionej informacji handlowej (spam);</li>
            <li>Niedostarczania i niezamieszczania na Platformie treści zabronionych przez przepisy obowiązującego prawa lub przez postanowienia Regulaminu; </li>
            <li>Korzystania z  Platformy w sposób zgodny z przepisami obowiązującego prawa na terytorium Rzeczpospolitej Polskiej oraz postanowieniami Regulaminu; </li>
            <li>Korzystania z wszelkich materiałów i treści zamieszczonych w ramach Platformy jedynie w zakresie własnego użytku osobistego. Wykorzystanie ww. materiałów i treści w innym zakresie jest dopuszczalne wyłącznie na podstawie wyraźnej zgody udzielonej przez scarto.pl. </li></ul> </p>
        
<p>7. Użytkownik ponosi wyłączną odpowiedzialność za czynności dokonane w ramach i w związku z korzystaniem z Platformy. </p>

<p>8. Użytkownik jest zobowiązany niezwłocznie powiadomić Spółkę o każdym przypadku naruszenia jego praw w ramach korzystania przez niego z Platformy.</p>

<p>9. Scarto.pl może uniemożliwić Użytkownikowi pełne lub częściowe korzystanie z Platformy, jeżeli Użytkownik narusza postanowienia Regulaminu.  </p>

<p>10. Scarto.pl dokłada należytych starań w celu zapewnienia prawidłowego i nieprzerwanego funkcjonowania Platformy, jednakże zastrzega możliwość czasowego wstrzymania pracy Platformy ze względów technicznych lub przyczyn niezależnych.</p>

<p>11. Zakończenie korzystania z Platformy przez Użytkownika może nastąpić w następujących przypadkach:
            <ul>
            <li>z chwilą usunięcia wszystkich Ofert przez Użytkownika;</li>
            <li>z chwilą usunięcia Ofert przez scarto.pl, w przypadkach wskazanych w Regulaminie;    </li>
            <li>z chwilą zakończenia działalności Platformy; </li>
            <li>w sytuacji czasowego wstrzymania pracy Platformy. </li></ul></p>
            
<h2 style="font-size:12px;">III. ZAMIESZCZANIE OFERT</h2>

<p>1. Zamieszczanie Ofert przez Użytkownika na Platformie odbywa się na zasadzie art. 14 ustawy z dnia 18 lipca 2002 r. o świadczeniu usług drogą elektroniczną (Dz. U. z 2002 r., Nr 144, poz. 1204 ze zm.).</p>

<p>2. Prezentowane na stronach Platformy Oferty i ich treść nie stanowią oferty w rozumieniu art. 66 Kodeksu Cywilnego, a jedynie zaproszenia do zawarcia umowy w rozumieniu art. 71 Kodeksu Cywilnego. </p>
        
<p>3. Dodanie Oferty nie wymaga rejestracji ani logowania się.</p>

<p>4. Rejestracja następuje automatycznie po dodaniu Oferty. Użytkownik otrzymuje e-mailem login i hasło do konta, które umożliwia mu zarządzanie swoją Ofertą, jej usunięcie lub dokonywanie w niej zmian. </p>

<p>5. Dopuszczalne jest zamieszczenie tylko i wyłącznie jednej Oferty dotyczącej pojedynczego przedmiotu, zestawu przedmiotów, nieruchomości lub pojazdu. Ta sama rzecz nie może być przedmiotem dwóch lub więcej Ofert w tych samych lub w różnych miastach lub w tych samych lub różnych kategoriach. </p>

<p>6. Użytkownik zobowiązuje się, że prawidłowo oznaczy swoją Ofertę, jako Ofertę osoby fizycznej nie prowadzającej działalności gospodarczej lub jako Ofertę przedsiębiorcy (tj. osoby prawnej, jednostki organizacyjnej nieposiadającej osobowości prawnej, mogącej we własnym imieniu nabywać prawa oraz zaciągać zobowiązania oraz osoby fizycznej prowadzącej działalność gospodarczą).</p>
        
<p>7. Użytkownik zobowiązuje się do rzetelnego opisu przedmiotu. Opis powinien zgadzać się ze stanem faktycznym. W szczególności nie powinien wprowadzać w błąd co do stanu przedmiotu, pochodzenia, oryginalności, marki.</p>

<p>8. Użytkownik oświadcza i gwarantuje, że przysługują mu niepodzielnie i bez ograniczeń prawa autorskie, prawa pokrewne, prawa do wizerunków oraz wszelkie inne prawa własności intelektualnej, w stosunku do treści Ofert zamieszczanych na Platformie, jak również, że treści te nie naruszają praw osób trzecich, ani nie są niezgodne z obowiązującym prawem. Z powyższego tytułu Użytkownik ponosi pełną odpowiedzialność. W szczególności dotyczy to używania w tytułach i opisach przedmiotu chronionych znaków towarowych, do których używania Użytkownik nie ma zgody właściciela lub nie zachodzą okoliczności pozwalające na posługiwanie się znakiem towarowym przewidziane w Ustawie "Prawo własności przemysłowej" (Dz.U.2003.119.1117 z późniejszymi zmianami).</p>

<p>9. Użytkownik zobowiązuje się, że nie będzie zamieszczać zdjęć oferowanego przedmiotu opatrzonych znakiem graficznym (logotypem) innych serwisów internetowych, a zwłaszcza portali ogłoszeniowych.</p>
        
<p>10. Niedopuszczalne jest zamieszczanie obrazów nieprzedstawiających przedmiotu oferty. Zwłaszcza treści reklamowych, logotypów firm i serwisów internetowych. </p>
        
<p>11. Użytkownik zobowiązuje się, że nie będzie zamieszczać na Platformie Ofert, o ile zawierałyby one treści sprzeczne z prawem lub treści, których wykorzystywanie bądź posiadanie przez Spółkę byłoby nielegalne.</p>

<p>12. Użytkownik zobowiązuje się, że nie będzie zamieszczać na Platformie Ofert, o ile takie Oferty są przedmiotem praw osób trzecich, chyba że Użytkownik posiada oficjalną licencję lub zgodę od podmiotu uprawnionego do przesyłania lub zamieszczania takich Ofert.</p>

<p>13. Użytkownik zobowiązuje się, że nie będzie zamieszczać na Platformie:
           <ul>
            <li>Ofert fikcyjnych (nieprawdziwych);</li>
            <li>Ofert bez podanej ceny;</li>
            <li>Ofert oznaczonych danymi osobowymi innej osoby fizycznej lub danymi innego przedsiębiorcy. </li>
            </ul>
<p>14. Ponadto Użytkownik zobowiązuje się nie zamieszczać na Platformie:
            <ul><li>Ofert świadczenia usług, wynajmu i dzierżawy;    </li>
            <li>Ofert pracy;  </li>
            <li>Ofert wymiany; </li>
            <li>Ofert bezpłatnego wydania rzeczy (darowizny);   </li>
            <li>Ofert o charakterze towarzyskim;  </li>
            <li>Reklam, promocji, w szczególności reklam jakichkolwiek innych serwisów internetowych lub jakichkolwiek linków odsyłających do innych stron internetowych, zwłaszcza innych serwisów aukcyjnych lub ogłoszeniowych.</li></ul>  </p>

<p>15. Użytkownik zobowiązuje się do niezwłocznego usunięcia oferty z serwisu po jej dezaktualizacji lub dokonanej transakcji sprzedaży. </p>

<p>16. Scarto.pl może bez zgody Użytkownika i bez uprzedniego powiadomienia Użytkownika usunąć Oferty i inne treści umieszczane przez Użytkownika na Platformie.  </p>

<p>17. Scarto.pl nie ponosi odpowiedzialności za treść i zawartość Ofert, jak również wszelkich innych materiałów oraz informacji zamieszczonych na Platformie przez Użytkowników, w szczególności za ich wiarygodność, prawdziwość, wartość dla innych Użytkowników itd. </p>

<p>18. Scarto.pl nie ponosi również odpowiedzialności za hiperłącza do zasobów ujętych w treści Oferty.</p>

<p>19. Scarto.pl zastrzega sobie prawo do wykorzystywania aktywnych Ofert i ich treści dla celów marketingowych i promocyjnych związanych z funkcjonowaniem Platformy.</p>

<p>20. Spółka zastrzega sobie prawo do utrzymywania w bazie danych Ofert, których okres emisji się zakończył, w celu ich archiwizacji. </p>

<h2 style="font-size:12px;">IV. PRYWATNOŚĆ I POUFNOŚĆ</h2>

<p>1. Dane osobowe Użytkowników przetwarzane są przez Administratora w celu prowadzenia Platformy i zapewnienia jej sprawnego funkcjonowania. </p>

<p>2. Użytkownik może za pośrednictwem Platformy udostępnić swoje dane osobowe innym Użytkownikom. Udostępnienie danych jest dobrowolne i wiąże się jedynie z zamieszczaniem Ofert na Platformie. </p>

<p>3. Dla realizacji celów, o których mowa w ust. 2 powyżej, Użytkownik jest zobowiązany do podania następujących danych (dane obligatoryjne):
            
            <ul>
            <li>Imię</li>
            <li>Miejscowość</li>
            <li>Adres e-mail</li>
            <li>Numer telefonu</li>
            </ul>   </p>
        
<p>4. Użytkownikom Platformy ujawniane są dane osobowe innych Użytkowników jedynie w zakresie, w jakim zostały podane przez Użytkownika w formularzu dodawania Oferty z wyjątkiem adresu e-mail, który pozostaje niewidoczny dla Użytkowników korzystających z Platformy. </p>

<p>5. Użytkownik uprawniony jest do korzystania z danych udostępnionych mu przez innych Użytkowników Platformy wyłącznie w związku z korzystaniem z Platformy, komunikowaniem się z innymi Użytkownikami oraz zawieraniem z nimi transakcji. </p>

<p>6. Użytkownik nie ma prawa do zamieszczania w formularzu dodawania Oferty danych osobowych innych osób lub danych osobowych, które są nieprawdziwe. </p>

<p>7. Dane osobowe Użytkownika mogą być przetwarzane przez Administratora w celach marketingowych, w tym w celu kierowania informacji handlowej drogą elektroniczną na wskazany przez Użytkownika adres e-mail.</p>

<p>8. Każdy Użytkownik ma prawo dostępu do treści swoich danych osobowych, prawo do ich poprawiania, uzupełnienia oraz prawo żądania zaprzestania przetwarzania danych i ich usunięcia, zwracając się w tym celu pisemnie do Administratora lub korzystając w tym celu z funkcjonalności w ramach konta tworzonego na Platformie. W przypadku usunięcia danych warunkujących korzystanie z Platformy Użytkownik traci możliwość korzystania z Platformy.</p>

<p>9. Administrator oświadcza, iż dołoży starań, aby zapewnić Użytkownikowi wysoki poziom bezpieczeństwa w zakresie korzystania z Platformy, poprzez zastosowanie odpowiednich administracyjnych, technicznych i fizycznych zabezpieczeń danych przed ich przypadkowym lub bezprawnym zniszczeniem, utratą, nieupoważnionym ujawnieniem lub udostępnieniem. Niestety żaden sposób przekazywania danych przez Internet nie jest w pełni bezpieczny. Pomimo, iż Administrator dokłada starań na rzecz zabezpieczenia przekazywanych danych osobowych, nie może zagwarantować pełnego bezpieczeństwa transmisji przez Internet. Dlatego też wszelkie zdarzenia mające wpływ na bezpieczeństwo przekazu informacji, w tym np. dotyczące podejrzenia udostępnienia plików zawierających wirusy i innych plików o podobnych charakterze, należy zgłaszać na adres Administratora: kontakt@scarto.pl. </p>
        
<h2 style="font-size:12px;">V. Polityka cookies</h2>

<p>1. Podmiotem zamieszczającym informacje w formie plików cookies (tzw. ciasteczek) i innych podobnych technologii w urządzeniu końcowym Użytkownika oraz uzyskującym do nich dostęp jest operator serwisu scarto.pl  </p>

<p>2. Serwis nie zbiera w sposób automatyczny żadnych informacji, z wyjątkiem informacji zawartych w plikach cookies. Pliki cookies nie służą identyfikacji użytkownika i na ich podstawie nie jest ustalana tożsamość użytkownika.  </p>

<p>3. Pliki cookies (tzw. „ciasteczka”) stanowią dane informatyczne, w szczególności pliki tekstowe, które przechowywane są w urządzeniu końcowym Użytkownika Serwisu i przeznaczone są do korzystania ze stron internetowych Serwisu. Cookies zazwyczaj zawierają nazwę strony internetowej, z której pochodzą, czas przechowywania ich na urządzeniu końcowym oraz unikalny numer. </p>

<p>4. Pliki cookies wykorzystywane są w celu:
            <ul>
            <li>utrzymanie sesji Użytkownika Serwisu (po zalogowaniu), dzięki której Użytkownik nie musi na każdej podstronie Serwisu ponownie wpisywać loginu i hasła;</li>
            <li>tworzenia anonimowych statystyk, które pomagają zrozumieć, w jaki sposób Użytkownicy Serwisu korzystają z niego, co umożliwia ulepszanie struktury i zawartości (w tym treści reklamowych) bez identyfikacji użytkownika. Informacje w ten sposób zebrane w tym w szczególności raporty zainteresowań i raporty demograficzne Google Analytics nie są łączone z danymi osobowymi użytkowników serwisu  </li>
            <li>dostosowania zawartości stron internetowych Serwisu do preferencji Użytkownika; w szczególności pliki te pozwalają na funkcjonowanie mechanizmów schowka oraz listy ostatnio oglądanych elementów, które umożliwiają usunięcie tych informacji w dowolnym momencie</li>
            <li>emitowania reklam serwisu scarto.pl w innych serwisach internetowych w sieci Google Adsense za pomocą mechanizmu remarketingu </li>
            </ul> </p>
        
<p>5. Rodzaje plików cookies

            Z uwagi na czas życia cookies i innych podobnych technologii, stosujemy dwa zasadnicze rodzaje tych plików:
                <ul>
                <li>sesyjne - pliki tymczasowe przechowywane w urządzeniu końcowym Użytkownika do czasu wylogowania, opuszczenia strony internetowej i aplikacji lub wyłączenia oprogramowania (przeglądarki internetowej);  </li>
                <li>stałe - przechowywane w urządzeniu końcowym Użytkownika przez czas określony w parametrach plików cookies lub do czasu ich usunięcia przez Użytkownika.</li>
            </ul></p>
            
<p>6. Ze względu na cel, jakiemu służą pliki cookies i inne podobne technologie, stosujemy ich następujące rodzaje:
                <ul>
                <li> niezbędne do działania usługi i aplikacji - umożliwiające korzystanie z naszych usług, np. uwierzytelniające pliki cookies wykorzystywane w procesie logowania;</li>
                <li> pliki służące do zapewnienia bezpieczeństwa, np. wykorzystywane do wykrywania nadużyć w zakresie uwierzytelniania </li>
                <li> wydajnościowe - umożliwiające zbieranie informacji o sposobie korzystania ze stron internetowych i aplikacji;  </li>
                <li> funkcjonalne - umożliwiające "zapamiętanie" wybranych przez Użytkownika ustawień i personalizację interfejsu Użytkownika, np. w zakresie wybranego języka lub regionu, z którego pochodzi Użytkownik, rozmiaru czcionki, wyglądu strony internetowej i aplikacji itp.; </li>
                <li> reklamowe - umożliwiające dostarczanie Użytkownikom treści reklamowych bardziej dostosowanych do ich zainteresowań;</li>
                <li> statystyczne - służące do zliczana statystyk dotyczących stron internetowych i aplikacji. </li>
                </ul>  </p>
                
<h2 style="font-size:12px;">VI. Zarządzanie cookies</h2>

<p>1. W wielu przypadkach oprogramowanie służące do przeglądania stron internetowych (przeglądarka internetowa) domyślnie dopuszcza przechowywanie plików cookies w urządzeniu końcowym Użytkownika. Użytkownicy Serwisu mogą dokonać w każdym czasie zmiany ustawień dotyczących plików cookies. Ustawienia te mogą zostać zmienione w szczególności w taki sposób, aby blokować automatyczną obsługę plików cookies w ustawieniach przeglądarki internetowej bądź informować o ich każdorazowym zamieszczeniu w urządzeniu Użytkownika Serwisu.  </p>

<p>2. Szczegółowe informacje o możliwości i sposobach obsługi plików cookies dostępne są w ustawieniach oprogramowania (przeglądarki internetowej). </p>

<p>3. Operator Serwisu informuje, że ograniczenia stosowania plików cookies mogą wpłynąć na niektóre funkcjonalności dostępne na stronach internetowych Serwisu. </p>

<p>4. Pliki cookies zamieszczane w urządzeniu końcowym Użytkownika Serwisu i wykorzystywane mogą być również przez współpracujących z operatorem Serwisu reklamodawców oraz partnerów, w tym w szczególności systemów Google Analytics i DoubleClick.    </p>

<p>5. Więcej informacji na temat plików cookies dostępnych jest pod adresem http://wszystkoociasteczkach.pl/, w sekcji "Pomoc" w menu przeglądarki internetowej lub na stronach internetowych producentów oprogramowania:
     
     <ul>
            <li>Chrome</li>
            <li>Firefox</li>
            <li>Internet Explorer 8</li>
            <li>Internet Explorer 9 </li>
            <li>Internet Explorer 10</li>
            <li>Opera </li>
            <li>Safari</li>
     </ul>  </p>

<p>6. Użytkownik może zrezygnować z usługi Google Analytics dla reklam displayowych i dostosować reklamy w sieci reklamowej Google za pomocą "Ustawień reklam" dostępnych pod adresem: https://www.google.com/settings/ads po zalogowaniu do konta Google. </p>
   
<h2 style="font-size:12px;">VII. REKLAMACJE </h2>

<p>1. Wszelkie reklamacje związane z użytkowaniem Platformy należy przesłać na adres poczty elektronicznej: kontakt@scarto.pl. </p>

<p>2. Reklamacja powinna zawierać w swej treści: imię i nazwisko, adres poczty elektronicznej, jak również dokładny opis i powód reklamacji.</p>

<p>3. Scarto.pl rozpatruje reklamację w ciągu 7 dni roboczych od dnia jej otrzymania oraz informuje niezwłocznie Użytkownika, za pomocą poczty elektronicznej, o sposobie jej rozpatrzenia. W sytuacji, gdy podane w reklamacji dane lub informacje wymagają uzupełnienia, scarto.pl zwraca się, przed rozpatrzeniem reklamacji, do składającego reklamację o jej uzupełnienie. Czas udzielenia dodatkowych wyjaśnień Użytkownikowi przedłuża okres rozpatrywania reklamacji.  </p>

<p>4. Reklamacje będące następstwem niestosowania się do treści niniejszego Regulaminu nie będą przez scarto.pl rozpatrywane.</p>

<h2 style="font-size:12px;">VIII. POSTANOWIENIA KOŃCOWE</h2>

<p>1. Scarto.pl zastrzega sobie prawo do zmiany niniejszego Regulaminu w dowolnym czasie. Zmiany Regulaminu obowiązują od momentu umieszczenia ich na stronie internetowej Platformy z zastrzeżeniem, że publikacja Ofert zamieszczonych przed wejściem w życie zmiany odbywa się na dotychczasowych zasadach. Zmiany uważane są za zaakceptowane przez Użytkownika z momentem skorzystania przez niego z Platformy. </p>

<p>2. Usługodawca zastrzega, że Platforma, a w szczególności rozwiązania nawigacyjne, wybór i układ prezentowanych w ramach Platformy treści, logotypy, elementy graficzne, interaktywne aplikacje, materiały audio i video stanowią przedmiot praw wyłącznych Usługodawcy.  </p>

<p>3. Postanowienia niniejszego Regulaminu podlegają prawu polskiemu. W kwestiach nieuregulowanych Regulaminem stosuje się przepisy Kodeksu Cywilnego i innych ustaw.</p>
</div>