<!DOCTYPE html>
<html lang="pl">
<head>
	<META NAME="ROBOTS" CONTENT="NOINDEX, FOLLOW">
<link href='http://fonts.googleapis.com/css?family=Signika:600,400,300&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>scarto</title>
  <meta name="description" content="Bezpłatne ogłoszenia motoryzacyjne." >
      <link href="/css/bootstrap.css" rel="stylesheet">
    <script type="text/javascript" src="/js/jquery.js"></script> 
    <script type="text/javascript" src="/js/bootstrap.js"></script> 
    <script type="text/javascript" src="/js/typeahead.js"></script>   
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/icon2.ico" type="image/x-icon">
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/css/style1.css" rel="stylesheet">
	<script src="/js/bootstrap-tab.js"></script>
	<script src="/js/bootstrap-collapse.js"></script>
    <script src="/js/imgLiquid-min.js"></script>
 <script type="text/javascript">
 $(function() {
$(".image").click(function() {
var image = $(this).attr("rel");
$('#image').hide();
$('#image').fadeIn('slow');
$('#image').html('<img src="' + image + '"/>');
return false;
	});
});
</script>
<script>
$(function() {
    $(".imgLiquidFill").imgLiquid({
        fill: true,
        horizontalAlign: "center",
        verticalAlign: "top"
    });    
    $(".imgLiquidNoFill").imgLiquid({
        fill: false,
        horizontalAlign: "center",
        verticalAlign: "50%"
    });
});
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41054268-1', 'scarto.pl');
  ga('send', 'pageview');

</script>

<script>
$(document).ready(function() {

$('input.form-controlxxx').typeahead({
  name: 'searchboxxxx',
  remote : 'osobowe/searchbox?query=%QUERY'
});
})
</script>


    <script type="text/javascript">

    $(document).ready(function(){

        $("#myNav").affix({

            offset: { 

                top: 190 

            }

        });

    });

    </script>

	
 
 
</head>
<body>

    <div class="navbar-wrapper" style="height:45px;background-color:#fff;">
		<div style="float:left;margin-left:105px;padding:0px;color:#fff;font-size:25px;font-family: 'Signika', Arial, serif; font-weight: 400;">
		<a href="/" style='text-decoration:none;'>scarto.pl<br />
		<p style='line-height:0.1;margin-bottom:0px;margin-top:0px;padding-top:0px;font-size:14px;color:#7A7A7A;'>
			ogłoszenia motoryzacyjne
		</p></a>
		<!----<img src='img/logo.png' />--->
		
		</div>
		<div style='float:right;margin-right:110px;'>
					<ul class="nav nav-pills" style='margin-top:8px;margin-bottom:5px;'>
			<!---<li class="active">-->
			<li class='active'><a href="/ogloszenia/dodaj" style='padding:8px 10px;'>dodaj ogłoszenie</a></li>
			  
			<?php 
			$val = $this->logStatus();
			
			if($val==1){
			?>
			<li><a tabindex="-1" href="/users" style='padding:8px 10px;'>konto</a></li>
			<li><a tabindex="-1" href="/users/logout/index" style='padding:8px 10px;'>wyloguj</a></li>
			<?php } elseif($val==0) { ?>
			<li><a tabindex="-1" href="/users/login/index" style='padding:8px 10px;'>logowanie</a></li>	
			<li><a tabindex="-1" href="/users/register/index" style='padding:8px 10px;'>rejestracja</a></li>
			<?php }?>
    
    
		</ul>

		</div>
	</div>
  

  	<!--- START MENU LEFT -->


    <div class="container marketing">
	
	<div style='width:160px;height:100%;float:left;margin-top:30px;padding:0px;'>
		
	<div style="background-color:#fff;padding:10px;font-family: 'Signika', Arial, serif; font-weight: 400;height:350px;">	
	
    <h2 style="margin-top:0px;font-family: 'Signika', Arial, serif; font-weight: 400;color:#7A7A7A;padding-top:5px;padding-bottom:4px;">
	<span class="glyphicon glyphicon-folder-open" style="margin-right:5px;"> </span> menu</h2> 


 <ul class="nav">
  <li><a href="/users">ogłoszenia</a></li>
  </ul>
  

    </div>   
	
		</div>
	
	
	<div id='right-side' style='float:right;width:970px;margin-top:30px;'>	
            <?php echo $this->content; ?>
    
	</div>

	
    </div><!-- /.container -->



  
      
           <div class="navbar-wrapper" style="width:100%;height:110px;background-color:#000;margin-top:25px;" id="bottomsite">
			<div style='margin-left:250px;'>	
             <p><strong>Dowiedz się więcej:</strong>
             <ul style="list-style-type: none;">			
			 <li><a href="/ogloszenia/about" style="color:#ccc;font-size:10px;">O serwisie</a></li>
             <li><a href="/ogloszenia/regulamin" style="color:#ccc;font-size:10px;">Regulamin</a></li>
             
             <li><a href="mailto:kontakt@scarto.pl" style="color:#ccc;font-size:10px;">Kontakt</a></li>
             </ul>
             Copyright © 2014 scarto.pl | Korzystanie z serwisu oznacza akceptację <a href="/ogloszenia/regulamin" style="color:#ccc;font-size:10px;">regulaminu</a>.
             </div>
    
         </div>
         

</body>
</html>